### PR TITLE
USE_NETCDF3/4 -> USE_NETCDF

### PR DESCRIPTION
**Pull request by webisu**
#227 merge USE_NETCDF3 and USE_NETCDF4 -> USE_NETCDF
eliminate USE_HDF5
default is classic. Use -nc4 to enable netcdf4.  Should allow builds with/without hdf5.

### CODE REVIEW

**Review by edwardhartnett — APPROVED** [review]
Looks good. Nice cleanup.

**Comment by webisu** [comment]
Ed,
   Having problems with spack.  Tried fixes but nothing is working.
Wesley

**Comment by edwardhartnett** [comment]
Seems to be working now. Still need help?

**Comment by webisu** [comment]
If it works, then it is ok.

**Pull request merged**
