### PR TITLE
Adding tests which test use of ip external library

### PR DESCRIPTION
**Pull request by AlysonStahl-NOAA**
Part of #103

### CODE REVIEW

**Review by edwardhartnett — APPROVED** [review]
Nice.

**Comment by edwardhartnett** [comment]
Is this ready to merge?

**Comment by AlysonStahl-NOAA** [comment]
> Is this ready to merge?

Nope, not yet. I'm working on adding some of Wesley's unmerged changes that make this compatible with the current version of the ip library. The test I have isn't actually working, I was just testing some things on the CI.

**Comment by edwardhartnett** [comment]
What's the status of this PR?

**Comment by AlysonStahl-NOAA** [comment]
> What's the status of this PR?

From what I understood Wesley was taking over transferring his changes for the newer versions of the ip library. I've been waiting for those changes to complete before I continued with this.

**Comment by edwardhartnett** [comment]
It would be great if this PR could be fixed and merged soon. More testing is more good!

**Pull request merged**
