### PR TITLE
fixed typo

### PR DESCRIPTION
**Pull request by edwardhartnett**

### CODE REVIEW

**Review by AlysonStahl-NOAA — COMMENTED** [review]
Can you tell what's causing this error? It's happening with every run now, but all of the checks passed before.
>==> Error: unrecognized arguments: --allow-root
Error: Process completed with exit code 1.

**Comment by edwardhartnett** [comment]
@AlexanderRichert-NOAA what's up with the spack build here?

**Comment by AlexanderRichert-NOAA** [comment]
Please try rerunning. It relates to a recently deprecated Spack command option.

**Comment by AlysonStahl-NOAA** [comment]
That did it. Thanks!

**Review by AlysonStahl-NOAA — APPROVED** [review]

**Pull request merged**
