### PR TITLE
Check for HDF5 in Cmake

### LINKED ISSUE #230: add check for HDF5 capability to CMake build
Here's an example from the netcdf-fortran CMakeLists.txt:

https://github.com/Unidata/netcdf-fortran/blob/6302daa1376f076add3d97794195d070ab81fdd9/CMakeLists.txt#L477

(But first check to see if it's something that FindNetCDF.cmake already returns as a CMake variable.)

### PR DESCRIPTION
**Pull request by AlysonStahl-NOAA**
Fixes #230

### CODE REVIEW

**Comment by AlysonStahl-NOAA** [comment]
@edwardhartnett This check appears to be working, but is there more to this?

**Comment by edwardhartnett** [comment]
Yes, now that we know whether HDF5 is present, @webisu what pre-processor should be set to tell the wgrib2 code that netCDF/HDF5 files are or are not available?

**Comment by webisu** [comment]
The config.c file no longer details the status of the HDF5 library.
Consequently the wgrib2 no longer uses the "USE_HDF5" preprocessor variable.

When the code tries to create a compressed netcdf file, the error message
was
upgraded to mention that the error occurred while creating a compressed
file.
Didn't know how to determine whether the hdf5 library was available.

**Comment by edwardhartnett** [comment]
OK, let's do the release!

The point is mostly moot in any case. All NOAA machines will have netCDF with HDF5, as indeed with almost all netCDF installs. So I think the decision is not to worry about it any further.

**Comment by AlysonStahl-NOAA** [comment]
Ok, so we are not including this PR in the release?

**Comment by edwardhartnett** [comment]
No I mean merge this and then release.

**Review by edwardhartnett — APPROVED** [review]

**Pull request merged**
