### PR TITLE
Add several NCEP grids

### PR DESCRIPTION
**Pull request by austincrosswx**
Add standard NCEP grids:
- HRRR 3 km
- NAM 12 km
- 130 (RAP 13 km)
- 132 (SREF 16 km)
- 187 (RTMA 2.5 km)
- 197 (CONUS NDFD 5 km)
- 236 (CONUS 40 km)

Add grid description comments for NCEP grids 2, 3, 4, 45, 98, 126, 184, 194, 221, 230, 236, 242, 249

From some of our local work here at NCEP/Aviation Weather Center

### CODE REVIEW

**Comment by webisu** [comment]
The official grid definition
https://www.nco.ncep.noaa.gov/pmb/docs/on388/tableb.html
is based on the grib1 standard which has its precision limited to
millidegrees.  The grib2 standard uses microdegree precision.

  Using wgrib2 to regrid the new grids, you want the resultant grid
definition match the official products exactly.  This can be checked by
wgrib2 FILE -checksum 3.    If the grid definition doesn't match
exactly, wgrib2 will not average fields (outside of -rpn).

So this welcome change needs to be checked with existing official
grib2 files.  Perhaps check with the model developers to get their
(un)documented grid definitions. (This is an EMC task.) Wesley

**Comment by edwardhartnett** [comment]
Thanks for the contribution.

Are these new grid definitions used in any official products? If so, which ones? We would like to take a look.

**Comment by austincrosswx** [comment]
Yes, the new grids are used by officially distributed model output from NCO. AWC in particular uses the HRRR, RTMA, and NDFD definitions to place data on a common grid.

**Review by AlysonStahl-NOAA — DISMISSED** [review]

**Comment by edwardhartnett** [comment]
But tests are needed...

**Comment by edwardhartnett** [comment]
@AlysonStahl-NOAA and @webisu will assist with testing...

**Review by edwardhartnett — APPROVED** [review]

**Pull request merged**
