### PR TITLE
Added more tests using FTP

### PR DESCRIPTION
**Pull request by AlysonStahl-NOAA**
Part of #118

### CODE REVIEW

**Comment by edwardhartnett** [comment]
Failing because:

0s
Run mkdir ~/data
mkdir: cannot create directory ‘/home/runner/data’: File exists
Error: Process completed with exit code [1](https://github.com/NOAA-EMC/wgrib2/actions/runs/8913808379/job/24480074466?pr=124#step:13:1).


I don't understand what this is failing.

I suggest you first remove the data caching and see if it works downloading everything every time. Then we can circle back around to get the cache working...

**Comment by edwardhartnett** [comment]
If this is adding a large test file (> 2 GB) from FTP then also add an additional CMake option in the main CMake file:

option(FTP_LARGE_TEST_FILES "Fetch and test with very large files on FTP site." OFF)

Then only get the large test file if this additional option is present.

**Comment by AlysonStahl-NOAA** [comment]
> Failing because:
> 
> 0s Run mkdir ~/data mkdir: cannot create directory ‘/home/runner/data’: File exists Error: Process completed with exit code [1](https://github.com/NOAA-EMC/wgrib2/actions/runs/8913808379/job/24480074466?pr=124#step:13:1).
> 
> I don't understand what this is failing.
> 
> I suggest you first remove the data caching and see if it works downloading everything every time. Then we can circle back around to get the cache working...

I fixed this issue in another pull request which has since been merged. It should be working now.

**Comment by AlysonStahl-NOAA** [comment]
> If this is adding a large test file (> 2 GB) from FTP then also add an additional CMake option in the main CMake file:
> 
> option(FTP_LARGE_TEST_FILES "Fetch and test with very large files on FTP site." OFF)
> 
> Then only get the large test file if this additional option is present.

This option already exists in the main CMake file and is checked for in the CMake file in the tests folder.

**Pull request merged**
