### PR TITLE
Add Spack-based CI workflow + recipe

### LINKED ISSUE #112: support spack build and testing
We need to add the wgrib2 package file to this repo, and set up testing with it, just as we have done for the NCEPLIBS. This will allow us to manage the spack package file with releases.

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
This PR adds a Spack-based CI workflow, including an authoritative copy of the recipe (updated for CMake).

Fixes #112

### CODE REVIEW

**Comment by AlexanderRichert-NOAA** [comment]
@edwardhartnett this is in pretty good shape, and I've tested a bunch of the spack variant related to dependencies. One thing that isn't working is if I enable the Fortran API and/or the library. I'm getting `wgrib2/ftn_api/fort_wgrib2.c:43: undefined reference to 'wgrib2'`. Any idea what that might be about?

**Comment by edwardhartnett** [comment]
@webisu any clue as to the build problems @AlexanderRichert-NOAA reports?

@AlexanderRichert-NOAA I think we should get this merged without the broken options, so we have something...

**Comment by AlexanderRichert-NOAA** [comment]
Okay, just updated. Users won't be able to apply build variants that aren't currently working.

**Comment by AlexanderRichert-NOAA** [comment]
The one remaining issue I can see is that USE_IPOLATES is no longer getting defined for the preprocessor. Is it your intent to only ever use ip or nothing, and have it set as on/off? If so, I think we need to add something like `list(APPEND definitions_list -DUSE_IPOLATES` under the `if(USE_IPOLATES)` block in CMakeLists.txt. If that sounds good I can add it to this PR.

**Review by AlysonStahl-NOAA — APPROVED** [review]

**Pull request merged**
