### PR TITLE
removing some of the tarballs

### PR DESCRIPTION
**Pull request by AlysonStahl-NOAA**
Part of #69 
Part of #65

### CODE REVIEW

**Comment by edwardhartnett** [comment]
Go ahead and delete the build.yml file in the workflows. It builds with the old makefile and we don't need to test it.

**Comment by AlysonStahl-NOAA** [comment]
> Go ahead and delete the build.yml file in the workflows. It builds with the old makefile and we don't need to test it.

Ok, will do. It looks like this makefile is the only place where the tarballs are even referenced or used. Are we going to want to remove this old makefile or just update it to look for the libraries?

**Comment by edwardhartnett** [comment]
Nice!

**Comment by edwardhartnett** [comment]
Is this ready to merge?

**Comment by AlysonStahl-NOAA** [comment]
> Is this ready to merge?

It should be.

Unless you want me to remove the old makefile?

**Pull request merged**
