### PR TITLE
Link lib and exe to the object library for correct transitive dependencies

### PR DESCRIPTION
**Pull request by kgerheiser**

### CODE REVIEW

**Review by edwardhartnett — APPROVED** [review]

**Comment by edwardhartnett** [comment]
Is there an issue for this PR?

**Comment by kgerheiser** [comment]
This

 https://github.com/NOAA-EMC/NCEPLIBS-wgrib2/issues/29

But to a different branch

**Review by GeorgeGayno-NOAA — CHANGES_REQUESTED** [review]
Kyle, I can't get the executable to build on Cray or Dell.  I get references to missing splib (and hdf5?)  objects.  The library builds fine, however.  I am using the 'build_all.sh', which is how NCO will build.

**Comment by kgerheiser** [comment]
Fixed. I forgot that this branch had some changes with static linking and HDF5.

Successfully built on WCOSS Dell

**Review by GeorgeGayno-NOAA — APPROVED** [review]
Successfully built the branch on Cray and Dell.  Matt Pyle verified it is working with his release/ops-hrefv3.1 branch.   Ready to merge.

**Pull request merged**
