### PR TITLE
rename top level "wgrib2" directory as "src"

### LINKED ISSUE #148: change top-level directory from "wgrib2" to "src"
In accordance with NCO standards and normal practice, let's name the main source directory src, instead of wgrib2.

wgrib2 is the name of the entire project, not just the source code.

### PR DESCRIPTION
**Pull request by AlysonStahl-NOAA**
Fixes #148

### CODE REVIEW

**Comment by edwardhartnett** [comment]
Let's not merge until after #143 is merged.

**Comment by edwardhartnett** [comment]
This looks messed up - there are too many changed files in this PR.

I suggest you abandon this one and start over...

**Comment by AlysonStahl-NOAA** [comment]
> This looks messed up - there are too many changed files in this PR.
> 
> I suggest you abandon this one and start over...

Most of those file changes are just all of the files that were under the wgrib2 subdirectory are now under the src subdirectory. Some extra files (especially tests) contained a reference to the wgrib2 executable which was under wgrib2/ so those needed to be updated as well.

**Comment by AlysonStahl-NOAA** [comment]
I am noticing some things that appear messed up after the last few merges. I will open a new PR and try this again after #145 is completed

**Pull request closed without merging**
