### PR TITLE
add to inv for pdt 49 #273

### PR DESCRIPTION
**Pull request by webisu**
The inventory for PDT 49 should show aerosol size.  Needed to fix Aerosol.c because it was hardwired for PDT=48. (The code is old.)  The inventory is controlled by Extname.c  Includes test.

Part of #273

### CODE REVIEW

**Comment by edwardhartnett** [comment]
Can we have an issue for this please?

**Comment by webisu** [comment]
When I switch the UPP configuration to generate GFS grib2 files, there is
no issue with dumping the aerosol wavelength.
================================
***@***.*** post_gfs_2023080300$ pwd
/u/wen.meng/ptmp/post_gfs_2023080300
***@***.*** post_gfs_2023080300$ wgrib2 GFSPRS.GrbF09 -match PMTF
8:6766731:d=2023080300:PMTF:1 hybrid level:9 hour fcst:aerosol=Dust
dry:*aerosol_size
>=2e-07,<2e-06:*
...

I am using wgrib2 v3.1.3 to dump GEFS grib2 files which generate from UPP.
It seems me that aerosol wavelength information is missing in the file
GFSPRS.GrbF09 at /u/wen.meng/ptmp/post_gefs_2023080300 on Cactus.
==================================
***@***.*** post_gefs_2023080300$ wgrib2 GFSPRS.GrbF09 -match PMTF
8:6766752:d=2023080300:PMTF:1 hybrid level:9 hour fcst:ENS=+1:aerosol=Dust
dry

The difference is that the GFS shows the "aerosol size".  This was added a
long time ago because
some grib files had grib messages with the same aerosol but different
sizes.    I added the aerosol size
the inventory to the
deterministic grib messages  (PDT=48).  Now the GEFS is creating aerosols
for the ensemble members
(PDT=49).  So aerosol size needs to be added.

**Comment by edwardhartnett** [comment]
I mean, reference the issue number in this PR (as I have done).

Issues are how we keep track of progress and prepare our release notes. If there is no issue, or the issue is not assigned to the correct version, then it will not be listed in the release notes.

**Comment by webisu** [comment]
I thought it was referenced by the issue number (#273).  What is #274?

**Review by AlysonStahl-NOAA — APPROVED** [review]

**Pull request merged**
