### PR TITLE
move get_*.sh files to new "wmo_scripts" directory

### LINKED ISSUE #210: move get_*.sh scripts to top-level subdirectory "wmo_scripts"
We can move these scripts out of our source code directory.

The scripts need to be modified to work from the new location.

### PR DESCRIPTION
**Pull request by AlysonStahl-NOAA**
Fixes #210

### CODE REVIEW

**Review by edwardhartnett — APPROVED** [review]
Did you test these? If so, how?

**Comment by AlysonStahl-NOAA** [comment]
Not in a rigorous capacity. I ran a few scripts to check that a file was being rewritten under the correct path.

**Comment by edwardhartnett** [comment]
What's the failing test all about?

**Comment by AlysonStahl-NOAA** [comment]
It has nothing to do with this particular PR. I believe it's another test that is passing inconsistently. Not sure if its for the same reason as the ones in #175, but it appears to be a difference in precision / calculation result. I just ran it again and it passes just fine.

**Pull request merged**
